### ISSUE TITLE
Create specifications for Philadelphia property tax relief screener questions

### ISSUE THREAD

**Issue by sierscse** [prestoncabe/dmn-benefit-toolbox#47]
Design the layout of questions for a Philadelphia property tax relief screener. This is an MVP-version of the screening. No bells and whistles.

**Comment by sierscse** [comment]
In progress:
https://docs.google.com/spreadsheets/d/1vUb3tAwAy8EijA5zdxsfJ59zXnkQ5BbumCw86Uz0anI/edit?usp=sharing

**Comment by prestoncabe** [comment]
@sierscse I made a first pass at adding questions to a new screener, just the Homestead and OOPA questions you had already on the spreadsheet for now.

[Video of me filling out the form](https://github.com/user-attachments/assets/cddef593-acab-42c8-9b81-d15e057da54b)

My thoughts:
- Overall: going well so far, no huge roadblocks, sparking lots of ideas for later improvements. 
- I am thinking that we will want to go ahead and enhance the enrollments checks so we can just collect enrollments on the form and then handle logic in the DMN (the DMN would still be compatible with the "override" mechanism we're familiar with). Right now I'm writing logic for this in the form, and that feels like a "smell".
- I spent the most time with the `equitableInterestInProperty` question... it seemed easiest to have checkboxes that collect the possible reasons and then it's overall `true` if there are any reasons... but definitely want to run this by you.
- Creating the form was fairly smooth overall, though I noticed two patterns that I would love to be able to abstract:
  - I'd love to have a custom "Yes/No question" input type so that I don't have to setup the radio button options manually for each new question (I just copy paste from an existing question for now, but it's annoying and unintuitive)
  - I'd love to have a custom FEEL function for hiding logic: something that will hide a question if another question is blank or true/false.  It's a little annoying and unintuitive to reach for the `list contains` function to do this...

Next steps:
- Get these two benefits working with the DMN, including rudimentary feedback about eligibility on the form. (probably will start a `/benefits/phillyTaxRelief` decision service that will be similar to the `benefits/all` example already in `benefits.dmn`)
- Add the rest of the questions (and hook up to eligibility) for the rest of the benefits (rudimentary "completeness").
- Take a few passes at improving eligibility feedback, question flow, and other design elements. _this is where I think we should spend time together in real time_
- test, test, test! _where I'm counting on your amazing ability to break stuff!_

Let me know if you have any thoughts about any of the above.

let's goooooo!

**Comment by prestoncabe** [comment]
deeming this complete...
