### ISSUE TITLE
LOOP: Determine correct income limit based on household size

### ISSUE THREAD

**Issue by prestoncabe** [prestoncabe/dmn-benefit-toolbox#56]
from #51:
> Initially LOOP was set up with the idea of entering incomes per person. Now that it's collecting primary/spouse income vs all other income for in the household as one amount, we'll need a way to determine HH size for Loop to determine which income limit to use.

**Comment by prestoncabe** [comment]
@sierscse I think this would be a good one for you to attempt in the new year because it would involve adding a question to the screener, but it is also a relatively simple addition.  (Good introduction to that side of the project).

**Comment by sierscse** [comment]
- [ ] Update current and previous year income services to use inputs.householdSize
- [ ] Update ThunderClient tests and get them to pass
- [ ] Update Camunda form to add household size field
- [ ] Test Philly property tax screener with householdSize field updates

**Comment by sierscse** [comment]
@prestoncabe I liked your idea of changing the options based on marital status so I did a select drop down instead of number field. It will reset if you select '1' while marital status is false but then switch it to true. It will then show the first select a '2'. If you don't like it I can change back to a number field instead of a select drop down.
